CREATE TABLE `data_platform_payment_request_edi_for_smes_header_data`
(
      `ExchangedPaymentRequestDocumentIdentifier`                                varchar(16) NOT NULL,
      `PaymentRequestDocument`                                                   varchar(100) DEFAULT NULL,
      `ExchangedDocumentContextSpecifiedTransactionIdentifier`                   varchar(16) DEFAULT NULL,
      `DocumentContextSpecifiedTransactionIdentifierByZEDI`                      varchar(16) DEFAULT NULL,
      `ExchangedPaymentRequestDocumentTypeCode`                                  varchar(4) DEFAULT NULL,
      `ExchangedPaymentRequestDocumentIssueDateTime`                             datetime DEFAULT NULL,
      `NotePaymentContentText`                                                   varchar(200) DEFAULT NULL,
      `TradeSettlementPaymentEndToEndIdentifier`                                 varchar(16) DEFAULT NULL,
      `TradeSettlementPaymentRequestedExecutionDateTime`                         datetime DEFAULT NULL,
      `TradePayeeIdentifier`                                                     varchar(16) DEFAULT NULL,
      `TradePayeeGlobalIdentifier`                                               varchar(16) DEFAULT NULL,
      `TradePayeeName`                                                           varchar(200) DEFAULT NULL,
      `TradePayeeRegisteredIdentifier`                                           varchar(16) DEFAULT NULL,
      `PayeeTelephoneNumber`                                                     varchar(20) DEFAULT NULL,
      `TradePayerIdentifier`                                                     varchar(16) DEFAULT NULL,
      `TradePayerGlobalIdentifier`                                               varchar(16) DEFAULT NULL,
      `TradePayerName`                                                           varchar(200) DEFAULT NULL,
      `PayerTelephoneNumber`                                                     varchar(20) DEFAULT NULL,
      `TradeSettlementMonetarySummationPaymentTotalAmount`                       float(13) DEFAULT NULL,
      `TradeSettlementMonetarySummationBalanceOutAmount`                         float(13) DEFAULT NULL,
      `TradeSettlementMonetarySummationTaxTotalAmount`                           float(13) DEFAULT NULL,
      `TradeSettlementMonetarySummationIncludingTaxesTotalAmount`                float(13) DEFAULT NULL,
      `TradeSettlementMonetarySummationGrandTotalAmount`                         float(13) DEFAULT NULL,
      `TradeSettlementMonetarySummationNetLineTotalAmount`                       float(13) DEFAULT NULL,
      `SpecifiedBalanceOutIdentifier`                                            varchar(16) DEFAULT NULL,
      `SpecifiedBalanceOutReasonCode`                                            varchar(4) DEFAULT NULL,
      `SpecifiedBalanceOutReasonDescription`                                     varchar(200) DEFAULT NULL,
      `SpecifiedBalanceOutCalculatedAmount`                                      float(13) DEFAULT NULL,
      `TradeSettlementPaymentMethodTypeCode`                                     varchar(4) DEFAULT NULL,
      `TradeSettlementPaymentMethodPaymentMethodCode`                            varchar(4) DEFAULT NULL,
      `DebtorFinancialAccountIBANIdentifier`                                     varchar(16) DEFAULT NULL,
      `DebtorFinancialAccountName`                                               varchar(200) DEFAULT NULL,
      `DebtorFinancialAccountProprietaryIdentifier`                              varchar(16) DEFAULT NULL,
      `DebtorFinancialAccountTypeCode`                                           varchar(4) DEFAULT NULL,
      `CreditorFinancialAccountIBANIdentifier`                                   varchar(16) DEFAULT NULL,
      `CreditorFinancialAccountName`                                             varchar(200) DEFAULT NULL,
      `CreditorFinancialAccountProprietaryIdentifier`                            varchar(16) DEFAULT NULL,
      `CreditorFinancialAccountTypeCode`                                         varchar(4) DEFAULT NULL,
      `DebtorFinancialInstitutionBICIdentifier`                                  varchar(16) DEFAULT NULL,
      `DebtorFinancialInstitutionName`                                           varchar(200) DEFAULT NULL,
      `DebtorFinancialInstitutionJapanFinancialInstitutionCommonIdentifier`      varchar(16) DEFAULT NULL,
      `DebtorBranchFinancialInstitutionIdentifier`                               varchar(16) DEFAULT NULL,
      `DebtorBranchFinancialInstitutionName`                                     varchar(200) DEFAULT NULL,
      `CreditorFinancialInstitutionBICIdentifier`                                varchar(16) DEFAULT NULL,
      `CreditorFinancialInstitutionName`                                         varchar(200) DEFAULT NULL,
      `CreditorFinancialInstitutionJapanFinancialInstitutionCommonIdentifier`    varchar(16) DEFAULT NULL,
      `CreditorBranchFinancialInstitutionIdentifier`                             varchar(16) DEFAULT NULL,
      `CreditorBranchFinancialInstitutionName`                                   varchar(200) DEFAULT NULL,

      PRIMARY KEY (`ExchangedPaymentRequestDocumentIdentifier`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
